name: ExampleHR Time-Off Microservice CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Setting the environment variable at the workflow level to opt into Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        # Updating the runtime version to Node 24
        node-version: '24.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Check Linting & Formatting
      run: npm run lint

    - name: Run Unit & Integration Tests
      run: npm run test:cov # Running with coverage for proof of rigor

    - name: Upload Test Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/