name: ExampleHR Time-Off Microservice CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# We can keep this to ensure any other JS-based actions also move to 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      # Bumping to v5 to natively support Node 24
      uses: actions/checkout@v5

    - name: Setup Node.js environment
      # Bumping to v5 to natively support Node 24
      uses: actions/setup-node@v5
      with:
        node-version: '24.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Check Linting & Formatting
      run: npm run lint

    - name: Run Unit & Integration Tests
      run: npm run test:cov

    - name: Upload Test Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/